### ISSUE TITLE
Rework paginated results

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#180]
We're currently using `_totalInQuery` attribute under `data` to represent the size of the result set. It's a bit odd to have this part of our VO models. Instead, we should do something more akin to Spring Data [Page](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Page.html) and add attributes in the root object.

 - [x] deprecate `_totalInQuery` in the code and in the OpenAPI specification and schedule removal
 - [x] add a new `ResponseDataObject` or a subclass that would handle paginated results, let's think about something forward-compatible with Spring Data
 - [x] make computing the attributes generic for any Hibernate query. I really like the idea of doing `select m, count(m) from Model m` in a single query, but the return value have to be a bit more explicit than `List<Model>`. I'm thinking maybe a `Page<Model>` like Spring Data provides.

It can't be perfectly compatible because we're using `data` instead of `content`, but we could fullfill the rest of the data model, and make it very convenient for API clients to consume our pages.

```yaml
data: 
last: false
totalPages: 583
totalElements: 11644
sort: null # indicate how data is sorted
size: 20
number: 0
first: true # if this is the first page
numberOfElements: 20
```

Example: https://register.rare-diseases-catalyst-network.ca/api/genes

The next step is to apply this to all the endpoints that accept offset/limit as input. Most of them were easy to migrate, but they still need a thorough review. (this was described in a comment below)

 - [x] platform datasets
 - [x] platforms
 - [x] platform elements
 - [ ] platform elements' genes
 - [x] datasets
 - [ ] dataset DE results
 - [x] annotations datasets
 - [x] annotations datasets by taxon
 - [ ] genes (does not have offset/limit args yet)
 - [x] gene probes
 - [x] taxon (does not have offset/limit args yet), no need finally
 - [x] taxon datasets (taxon itself does not have pagination)
 - [x] result sets
 - [ ] phenotype evidences

**Comment by arteymix** [comment]
I've introduced a `Slice` data structure that fit the current approach for filtering, and I think we should respect the already established pagination scheme:

```yaml
data: [...]
size: 8 # size of data
offset: 0 # offset in original result set
limit: 20 # maximum number of results in this slice
sort: 
 - orderBy: propertyName
 - direction: ASC | DESC
totalElements: 1000
```

I'm finishing up the `FilteringVoEnabledDao` that will allow us to automate most of this in #164. The idea is to isolate the `loadValueObjectPreFilter` and make it return a `Slice<VO>` so that the API can use the extra information to produce the final response body.
